#include <raylib.h>

#include "image.h"

const color_t pico_colors[] = {
    PICO_0, PICO_1, PICO_2, PICO_3, PICO_4, PICO_5,
    PICO_6, PICO_7, PICO_8, PICO_9, PICO_10, PICO_11,
    PICO_12, PICO_13, PICO_14, PICO_15
};


bool export_to_png(image_t *this, const char *filename);

int main( int arg_count, char *args[] ) {
    image_t *image = &IMAGE_VALUE(128, 128);

    for (int i = 0; i < image->width * image->height; i++) {
        image->pixels[i] = PICO_0;
    }

    // draw a circle for each of the pico colors from color 1 to color 15
    for ( int i = 1; i < 16; i++ ) {
        int x = (i % 4) * 32 + 16;
        int y = (i / 4) * 32 + 16;
        image_draw_circle_filled(image, x, y, 12, pico_colors[i]);
    }

    image_save_path(image, "output.image_t");
    image = image_load_path("output.image_t");

    bool ok = export_to_png(image, "output.png");
    free(image);

    if (!ok) {
        fprintf(stderr, "Failed to export image to PNG\n");
        return 1;
    }
    return 0;
}

// helper function to convert color_t to Color
#define COLOR_T_TO_RGB(c) \
    ((Color) {CHANNEL_R(c), CHANNEL_G(c), CHANNEL_B(c), 255})
const Color palette[] = {
    COLOR_T_TO_RGB(0),
    COLOR_T_TO_RGB(1),
    COLOR_T_TO_RGB(2),
    COLOR_T_TO_RGB(3),
    COLOR_T_TO_RGB(4),
    COLOR_T_TO_RGB(5),
    COLOR_T_TO_RGB(6),
    COLOR_T_TO_RGB(7),
    COLOR_T_TO_RGB(8),
    COLOR_T_TO_RGB(9),
    COLOR_T_TO_RGB(10),
    COLOR_T_TO_RGB(11),
    COLOR_T_TO_RGB(12),
    COLOR_T_TO_RGB(13),
    COLOR_T_TO_RGB(14),
    COLOR_T_TO_RGB(15),
    COLOR_T_TO_RGB(16),
    COLOR_T_TO_RGB(17),
    COLOR_T_TO_RGB(18),
    COLOR_T_TO_RGB(19),
    COLOR_T_TO_RGB(20),
    COLOR_T_TO_RGB(21),
    COLOR_T_TO_RGB(22),
    COLOR_T_TO_RGB(23),
    COLOR_T_TO_RGB(24),
    COLOR_T_TO_RGB(25),
    COLOR_T_TO_RGB(26),
    COLOR_T_TO_RGB(27),
    COLOR_T_TO_RGB(28),
    COLOR_T_TO_RGB(29),
    COLOR_T_TO_RGB(30),
    COLOR_T_TO_RGB(31),
    COLOR_T_TO_RGB(32),
    COLOR_T_TO_RGB(33),
    COLOR_T_TO_RGB(34),
    COLOR_T_TO_RGB(35),
    COLOR_T_TO_RGB(36),
    COLOR_T_TO_RGB(37),
    COLOR_T_TO_RGB(38),
    COLOR_T_TO_RGB(39),
    COLOR_T_TO_RGB(40),
    COLOR_T_TO_RGB(41),
    COLOR_T_TO_RGB(42),
    COLOR_T_TO_RGB(43),
    COLOR_T_TO_RGB(44),
    COLOR_T_TO_RGB(45),
    COLOR_T_TO_RGB(46),
    COLOR_T_TO_RGB(47),
    COLOR_T_TO_RGB(48),
    COLOR_T_TO_RGB(49),
    COLOR_T_TO_RGB(50),
    COLOR_T_TO_RGB(51),
    COLOR_T_TO_RGB(52),
    COLOR_T_TO_RGB(53),
    COLOR_T_TO_RGB(54),
    COLOR_T_TO_RGB(55),
    COLOR_T_TO_RGB(56),
    COLOR_T_TO_RGB(57),
    COLOR_T_TO_RGB(58),
    COLOR_T_TO_RGB(59),
    COLOR_T_TO_RGB(60),
    COLOR_T_TO_RGB(61),
    COLOR_T_TO_RGB(62),
    COLOR_T_TO_RGB(63),
    COLOR_T_TO_RGB(64),
    COLOR_T_TO_RGB(65),
    COLOR_T_TO_RGB(66),
    COLOR_T_TO_RGB(67),
    COLOR_T_TO_RGB(68),
    COLOR_T_TO_RGB(69),
    COLOR_T_TO_RGB(70),
    COLOR_T_TO_RGB(71),
    COLOR_T_TO_RGB(72),
    COLOR_T_TO_RGB(73),
    COLOR_T_TO_RGB(74),
    COLOR_T_TO_RGB(75),
    COLOR_T_TO_RGB(76),
    COLOR_T_TO_RGB(77),
    COLOR_T_TO_RGB(78),
    COLOR_T_TO_RGB(79),
    COLOR_T_TO_RGB(80),
    COLOR_T_TO_RGB(81),
    COLOR_T_TO_RGB(82),
    COLOR_T_TO_RGB(83),
    COLOR_T_TO_RGB(84),
    COLOR_T_TO_RGB(85),
    COLOR_T_TO_RGB(86),
    COLOR_T_TO_RGB(87),
    COLOR_T_TO_RGB(88),
    COLOR_T_TO_RGB(89),
    COLOR_T_TO_RGB(90),
    COLOR_T_TO_RGB(91),
    COLOR_T_TO_RGB(92),
    COLOR_T_TO_RGB(93),
    COLOR_T_TO_RGB(94),
    COLOR_T_TO_RGB(95),
    COLOR_T_TO_RGB(96),
    COLOR_T_TO_RGB(97),
    COLOR_T_TO_RGB(98),
    COLOR_T_TO_RGB(99),
    COLOR_T_TO_RGB(100),
    COLOR_T_TO_RGB(101),
    COLOR_T_TO_RGB(102),
    COLOR_T_TO_RGB(103),
    COLOR_T_TO_RGB(104),
    COLOR_T_TO_RGB(105),
    COLOR_T_TO_RGB(106),
    COLOR_T_TO_RGB(107),
    COLOR_T_TO_RGB(108),
    COLOR_T_TO_RGB(109),
    COLOR_T_TO_RGB(110),
    COLOR_T_TO_RGB(111),
    COLOR_T_TO_RGB(112),
    COLOR_T_TO_RGB(113),
    COLOR_T_TO_RGB(114),
    COLOR_T_TO_RGB(115),
    COLOR_T_TO_RGB(116),
    COLOR_T_TO_RGB(117),
    COLOR_T_TO_RGB(118),
    COLOR_T_TO_RGB(119),
    COLOR_T_TO_RGB(120),
    COLOR_T_TO_RGB(121),
    COLOR_T_TO_RGB(122),
    COLOR_T_TO_RGB(123),
    COLOR_T_TO_RGB(124),
    COLOR_T_TO_RGB(125),
    COLOR_T_TO_RGB(126),
    COLOR_T_TO_RGB(127),
    COLOR_T_TO_RGB(128),
    COLOR_T_TO_RGB(129),
    COLOR_T_TO_RGB(130),
    COLOR_T_TO_RGB(131),
    COLOR_T_TO_RGB(132),
    COLOR_T_TO_RGB(133),
    COLOR_T_TO_RGB(134),
    COLOR_T_TO_RGB(135),
    COLOR_T_TO_RGB(136),
    COLOR_T_TO_RGB(137),
    COLOR_T_TO_RGB(138),
    COLOR_T_TO_RGB(139),
    COLOR_T_TO_RGB(140),
    COLOR_T_TO_RGB(141),
    COLOR_T_TO_RGB(142),
    COLOR_T_TO_RGB(143),
    COLOR_T_TO_RGB(144),
    COLOR_T_TO_RGB(145),
    COLOR_T_TO_RGB(146),
    COLOR_T_TO_RGB(147),
    COLOR_T_TO_RGB(148),
    COLOR_T_TO_RGB(149),
    COLOR_T_TO_RGB(150),
    COLOR_T_TO_RGB(151),
    COLOR_T_TO_RGB(152),
    COLOR_T_TO_RGB(153),
    COLOR_T_TO_RGB(154),
    COLOR_T_TO_RGB(155),
    COLOR_T_TO_RGB(156),
    COLOR_T_TO_RGB(157),
    COLOR_T_TO_RGB(158),
    COLOR_T_TO_RGB(159),
    COLOR_T_TO_RGB(160),
    COLOR_T_TO_RGB(161),
    COLOR_T_TO_RGB(162),
    COLOR_T_TO_RGB(163),
    COLOR_T_TO_RGB(164),
    COLOR_T_TO_RGB(165),
    COLOR_T_TO_RGB(166),
    COLOR_T_TO_RGB(167),
    COLOR_T_TO_RGB(168),
    COLOR_T_TO_RGB(169),
    COLOR_T_TO_RGB(170),
    COLOR_T_TO_RGB(171),
    COLOR_T_TO_RGB(172),
    COLOR_T_TO_RGB(173),
    COLOR_T_TO_RGB(174),
    COLOR_T_TO_RGB(175),
    COLOR_T_TO_RGB(176),
    COLOR_T_TO_RGB(177),
    COLOR_T_TO_RGB(178),
    COLOR_T_TO_RGB(179),
    COLOR_T_TO_RGB(180),
    COLOR_T_TO_RGB(181),
    COLOR_T_TO_RGB(182),
    COLOR_T_TO_RGB(183),
    COLOR_T_TO_RGB(184),
    COLOR_T_TO_RGB(185),
    COLOR_T_TO_RGB(186),
    COLOR_T_TO_RGB(187),
    COLOR_T_TO_RGB(188),
    COLOR_T_TO_RGB(189),
    COLOR_T_TO_RGB(190),
    COLOR_T_TO_RGB(191),
    COLOR_T_TO_RGB(192),
    COLOR_T_TO_RGB(193),
    COLOR_T_TO_RGB(194),
    COLOR_T_TO_RGB(195),
    COLOR_T_TO_RGB(196),
    COLOR_T_TO_RGB(197),
    COLOR_T_TO_RGB(198),
    COLOR_T_TO_RGB(199),
    COLOR_T_TO_RGB(200),
    COLOR_T_TO_RGB(201),
    COLOR_T_TO_RGB(202),
    COLOR_T_TO_RGB(203),
    COLOR_T_TO_RGB(204),
    COLOR_T_TO_RGB(205),
    COLOR_T_TO_RGB(206),
    COLOR_T_TO_RGB(207),
    COLOR_T_TO_RGB(208),
    COLOR_T_TO_RGB(209),
    COLOR_T_TO_RGB(210),
    COLOR_T_TO_RGB(211),
    COLOR_T_TO_RGB(212),
    COLOR_T_TO_RGB(213),
    COLOR_T_TO_RGB(214),
    COLOR_T_TO_RGB(215),
    COLOR_T_TO_RGB(216),
    COLOR_T_TO_RGB(217),
    COLOR_T_TO_RGB(218),
    COLOR_T_TO_RGB(219),
    COLOR_T_TO_RGB(220),
    COLOR_T_TO_RGB(221),
    COLOR_T_TO_RGB(222),
    COLOR_T_TO_RGB(223),
    COLOR_T_TO_RGB(224),
    COLOR_T_TO_RGB(225),
    COLOR_T_TO_RGB(226),
    COLOR_T_TO_RGB(227),
    COLOR_T_TO_RGB(228),
    COLOR_T_TO_RGB(229),
    COLOR_T_TO_RGB(230),
    COLOR_T_TO_RGB(231),
    COLOR_T_TO_RGB(232),
    COLOR_T_TO_RGB(233),
    COLOR_T_TO_RGB(234),
    COLOR_T_TO_RGB(235),
    COLOR_T_TO_RGB(236),
    COLOR_T_TO_RGB(237),
    COLOR_T_TO_RGB(238),
    COLOR_T_TO_RGB(239),
    COLOR_T_TO_RGB(240),
    COLOR_T_TO_RGB(241),
    COLOR_T_TO_RGB(242),
    COLOR_T_TO_RGB(243),
    COLOR_T_TO_RGB(244),
    COLOR_T_TO_RGB(245),
    COLOR_T_TO_RGB(246),
    COLOR_T_TO_RGB(247),
    COLOR_T_TO_RGB(248),
    COLOR_T_TO_RGB(249),
    COLOR_T_TO_RGB(250),
    COLOR_T_TO_RGB(251),
    COLOR_T_TO_RGB(252),
    COLOR_T_TO_RGB(253),
    COLOR_T_TO_RGB(254),
    COLOR_T_TO_RGB(255),
};

bool export_to_png(image_t *this, const char *filename) {
    Image raylib_image = GenImageColor(this->width, this->height, BLACK);
    for ( int i = 0; i < this->width * this->height; i++ ) {
        color_t color = this->pixels[i];
        ImageDrawPixel(&raylib_image, i % this->width, i / this->width, palette[color]);
    }
    // Save the image to a file
    bool rc = ExportImage(raylib_image, filename);
    UnloadImage(raylib_image);
    return rc;
}
